Graphics/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('instagram', TemplateView.as_view(template_name='base/insta.html',extra_context={"instagram_profile_name": "complement_studios"}))
]

base/urls.py
from django.urls import path
from base.views import aboutView, clientView, contactView, index, send_message, videoDetailView, videoView, workView
app_name = 'base'

urlpatterns = [
    path('', index, name='index'),
    path('video', videoView, name='videos'),
    path('video/<uuid:uuid>', videoDetailView, name='video-details'),
    path('works', workView, name='works'),
    path('clients', clientView, name='clients'),
    path('about', aboutView, name='about'),
    path('contact', contactView, name='contact'),
    path('send-message', send_message, name='send_message'),
    
]

base/models.py
from django.db import models
from  embed_video.fields  import  EmbedVideoField
import uuid
from ckeditor.fields import RichTextField

SITES = (
    ('Youtube','Youtube'),
    ('Vimeo','Vimeo'),
)

# Create your models here.
class Video(models.Model):
    """ video model """
    uuid = models.UUIDField(primary_key = True, default = uuid.uuid4, editable = False)
    title = models.CharField(max_length=200)
    video_url = EmbedVideoField()
    site_name = models.CharField(max_length=50, choices=SITES)
    details = RichTextField(blank = True, null=True)
        
    def __str__(self):
        return self.title if self.title else 'video_{}'.format(self.id)
    
    class Meta:
        verbose_name_plural = 'Videos'
        


class CustomerMessage(models.Model):
    """ Messages model """
    
    email = models.EmailField()
    sender = models.CharField(max_length=100) 
    subject = models.CharField(max_length=100)
    body = models.TextField()
    created_on = models.DateField(auto_now_add=True)
    
    def __str__(self):
        return 'From: {} on subject: {}'.format(str(self.email), self.subject)
    
    

base/forms.py
from dataclasses import field
from email.message import Message
from django import forms

from base.models import CustomerMessage


class MessageForm(forms.ModelForm):
    class Meta:
        model=CustomerMessage
        fields = '__all__'

base/views.py
from django.contrib import messages
from django.http import HttpResponse
from django.shortcuts import redirect, render
from Graphics import settings
from base.forms import MessageForm
from base.globals import send_html_email

from .models import CustomerMessage, Video

# Create your views here.

def index(request):
    return render(request, 'base/index.html')

def videoView(request):
    v = Video.objects.all()
    context = {'v':v}
    return render(request, 'base/video.html', context)


def videoDetailView(request, uuid):
    v = Video.objects.filter(uuid=uuid).first()
    related_videos = Video.objects.filter(site_name=v.site_name)[:4]
    context = {'v':v, 'related_videos':related_videos}
    return render(request, 'base/video_details.html', context)

def workView(request):
    context = {}
    return render(request, 'base/works.html', context)


def clientView(request):
    context = {}
    return render(request, 'base/clients.html', context)

def contactView(request):
    context = {}
    return render(request, 'base/contact.html', context)

def aboutView(request):
    context = {}
    return render(request, 'base/about.html', context)

def send_message(request):
    # form = MessageForm()
    # if request.method == 'POST':
    #     form = MessageForm(request.POST)
        
        
    if request.POST:
        formData = request.POST.copy()
        name = formData.get('sender')
        sender = formData.get('email')
        subject = formData.get('subject')
        message = formData.get('body')
        to = settings.DEFAULT_FROM_EMAIL

        mail_context = {
            'message': message,
            'sender': sender,
            'name': name,
            'subject': subject,
        }

        contactData = CustomerMessage( sender=name, email=sender, subject=subject, body=message)
        contactData.save()
        messages.info(request, 'Message was mailed successfully, our team will get in touch with you as soon as possible')
        send_html_email([sender, ], subject,"emails/message.html", context=mail_context)
        
        # if form.is_valid():
        #     to_list = form.cleaned_data['sender']
        #     email = form.cleaned_data['email']
        #     subject = form.cleaned_data['subject']
            
        #     email_context = {
        #         'to_list':to_list,
        #         'email': email,
        #         'subject':subject,
        #     }
        #     form.save()
        #     print('saved')
        #     messages.info(request, 'Your concern/question was sent successfully, we will reach you as soon as possible')
        #     send_mail = send_html_email([to_list, ], 'Message Reception Acknowledgement', 'emails/message.html', email_context )    
        #     print('message was sent', send_mail)        
        #     if send_mail:
        #         form.save()
        #         messages.info(request, 'Your concern/question was sent successfully, we will reach you as soon as possible')
        #         return redirect('base:contact')
        #     else:
        #         print('failed to send', send_mail, form.errors)
        #         return redirect('base:contact')
                
        # else:
        #     print('failed', form.errors)
        #     messages.error(request, form.errors)
        #     form = MessageForm()
            
    return render(request, 'base/contact.html', context={})
    
    
        

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- =============== Bootstrap Core CSS =============== -->
    <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}" type="text/css">
    <!-- =============== fonts awesome =============== -->
    <link rel="stylesheet" href="{% static 'assets/font/css/font-awesome.min.css' %}" type="text/css">
    <!-- =============== Plugin CSS =============== -->
    <link rel="stylesheet" href="{% static 'assets/css/animate.min.css' %}" type="text/css">
    <!-- =============== Custom CSS =============== -->
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}" type="text/css">
    <!-- =============== Owl Carousel Assets =============== -->
    <link href="{% static 'assets/owl-carousel/owl.carousel.css' %}" rel="stylesheet">
    <link href="{% static 'assets/owl-carousel/owl.theme.css' %}" rel="stylesheet">
	
	<link rel="stylesheet" href="{% static 'assets/css/isotope-docs.css' %}" media="screen">
	<link rel="stylesheet" href="{% static 'assets/css/baguetteBox.css' %}">

    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css" rel="stylesheet">

</head>

 <!-- =============== Preloader =============== -->
 <div id="preloader">
    <div id="loading">
    <img width="256" height="32" src="{% static 'assets/img/loading-cylon-red.svg' %}">	
    </div>
</div>

<body class=''>   

    {% block top_nav %}
        {% include 'includes/top-nav.html' %}
    {% endblock %}

    {% block content %}
    
    {% endblock content %}


    {% block footer %}
        {% include 'includes/footer.html' %}
    {% endblock %}
        
	<!-- =============== jQuery =============== -->
    <script src="{% static 'assets/js/jquery.js' %}"></script>
	 <script src="{% static 'assets/js/isotope-docs.min.js' %}"></script>
    <!-- =============== Bootstrap Core JavaScript =============== -->
    <script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
    <!-- =============== Plugin JavaScript =============== -->
    <script src="{% static 'assets/js/jquery.easing.min.js' %}"></script>
    <script src="{% static 'assets/js/jquery.fittext.js' %}"></script>
    <script src="{% static 'assets/js/wow.min.js' %}"></script> 
	<!-- =============== owl carousel =============== -->
    <script src="{% static 'assets/owl-carousel/owl.carousel.js' %}"></script>  
	<!-- Isotope does NOT require jQuery. But it does make things easier -->

<script src="{% static 'assets/js/baguetteBox.js' %}" async></script>
<script src="{% static 'assets/js/plugins.js' %}" async></script>
 
    <!-- =============== Custom Theme JavaScript =============== -->
    <script src="{% static 'assets/js/creative.js' %}">	</script> 
<script src="{% static 'assets/js/jquery.nicescroll.min.js' %}"></script>

<script>
  $(document).ready(function() {
  
	var nice = $("html").niceScroll();  // The document page (body)
	
	$("#div1").html($("#div1").html()+' '+nice.version);
    
    $("#boxscroll").niceScroll({cursorborder:"",cursorcolor:"#00F",boxzoom:true}); // First scrollable DIV

    $("#boxscroll2").niceScroll("#contentscroll2",{cursorcolor:"#F00",cursoropacitymax:0.7,boxzoom:true,touchbehavior:true});  // Second scrollable DIV
    $("#boxframe").niceScroll("#boxscroll3",{cursorcolor:"#0F0",cursoropacitymax:0.7,boxzoom:true,touchbehavior:true});  // This is an IFrame (iPad compatible)
	
    $("#boxscroll4").niceScroll("#boxscroll4 .wrapper",{boxzoom:true});  // hw acceleration enabled when using wrapper
    
  });
</script>
<script>
window.onload = function() {
    if(typeof oldIE === 'undefined' && Object.keys)
        hljs.initHighlighting();

    baguetteBox.run('.baguetteBoxOne');
    baguetteBox.run('.baguetteBoxTwo');
    baguetteBox.run('.baguetteBoxThree', {
        animation: 'fadeIn'
    });
    baguetteBox.run('.baguetteBoxFour', {
        buttons: false
    });
    baguetteBox.run('.baguetteBoxFive', {
        captions: function(element) {
            return element.getElementsByTagName('img')[0].alt;
        }
    });
};
</script>
</body>
</html>

templates/base/about.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<link rel="stylesheet" href="{% static 'css/contact.css' %}">

<div class='header_wrapper mb-4'>
    <h1 class="section-header">About</h1>
</div>
<section id="contact container mt-5 ">


    <section id="about" class="container" tyle='margin-top: 70px; margin-bottom: 70px'>
		<!-- =============== container =============== -->
        <div class="container">            
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-6 wow fadeInDown animated" data-wow-delay=".5s">
                   <h2>About Us</h2>
				   <p>Lorem ipsum dolor sit amet, netus pellentesque mauris, non quis adipiscing aliquam tortor nulla, ut dolor, mauris sem ultricies sed tellus ut aliquam. Donec vel sollicitudin orci mi ut, neque aliquam vel vel nostrum enim tristique, magna rhoncus. Dapibus purus eget cubilia eget, in ut in mi dui ipsum odio, nullam vestibulum aliquam fusce, dignissim venenatis ultricies sed mattis non, metus a libero et. Imperdiet aliquet. Vivamus malesuada, ultrices convallis, diam vitae pellentesque volutpat ante vitae amet, ac leo, arcu duis venenatis in auctor sit suscipit. </p>
				   <p>Integer sapien sed mauris nec, volutpat risus leo placerat elit at aliquet, a egestas ultrices, vitae non amet lacus etiam, malesuada pellentesque scelerisque. Neque fermentum parturient ante pede, a dui ut ultricies luctus non nobis, amet nibh et. Diam nunc in eleifend commodo ante, amet quam integer dolor sit volutpat faucibus, sed sem, et amet sed, vestibulum mollit et a ac nullam. Eu nunc voluptas risus dui et pellentesque.</p>
                  </div>
                  <div class="col-xs-12 col-sm-12 col-md-6 wow fadeInRight animated" data-wow-delay=".5s">
                     <img src="../../static/assets/img/about-img.jpg" style='z-index:1'/>               
                  </div>     
            </div>
        </div>   
		<!-- =============== container end =============== -->		
    </section>
</section>

{% endblock content %}

templates/base/clients.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<link rel="stylesheet" href="{% static 'css/contact.css' %}">
<link rel="stylesheet" href="{% static 'css/clients.css' %}">

<section id="contact container">
    <div class='header_wrapper mb-4'>
        <h1 class="section-header">Clients</h1>
    </div>
    <div class='wr d-flex justify-content-center'>
        <div class="grid ">
            <div>1</div>
            <div>2</div>
            <div>3</div>
            <div>4</div>
            <div>5</div>
            <div>6</div>
            <div>7</div>
            <div>8</div>
            <div>9</div>
          </div>
    </div>
</section>

{% endblock content %}

templates/base/contact.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<link rel="stylesheet" href="{% static 'css/contact.css' %}">

<section id="contact container" >
    <div class='header_wrapper '>
        <h1 class="section-header">Contact</h1>
    </div>
    
    <div class="contact-wrapper" style="margin:70px auto">
    
    <!-- Left contact page --> 
      
      <form id="contact-form " class="form-horizontal" role="form" method="post" action="{% url 'base:send_message' %}">
        {% for msg in messages %}
          <p class="text-success">{{ msg }}</p>
        {% endfor %}
        {% csrf_token %}
        {{ form.errors }}
         
        <div class="form-group">
          <div class="col-sm-12">
            <input type="text" class="form-control" id="name" placeholder="NAME" name="sender" value="" required>
          </div>
        </div>
  
        <div class="form-group">
          <div class="col-sm-12">
            <input type="email" class="form-control" id="email" placeholder="EMAIL" name="email" value="" required>
          </div>
        </div>
        
        <div class="form-group">
          <div class="col-sm-12">
            <input type="text" class="form-control" id="name" placeholder="SUBJECT" name="subject" value="" required>
          </div>
        </div>
  
        <textarea class="form-control" rows="8" placeholder="MESSAGE" name="body" required></textarea>
        
        <button class="btn btn-primary send-button" id="submit" type="submit" value="SEND">
          <div class="alt-send-button">
            <i class="fa fa-paper-plane"></i><span class="send-text">SEND</span>
          </div>
        
        </button>
        
      </form>
      
    <!-- Left contact page --> 
      
        <div class="direct-contact-container">
  
          <ul class="contact-list">
            <li class="list-item"><i class="fas fa-map-marker fa-2x"><span class="contact-text place">Nairobi, Kenya</span></i></li>
            
            <li class="list-item"><i class="fa fa-phone fa-2x"><span class="contact-text phone"><a href="tel:+254-712-345-678" title="Give me a call">(254) 712 345678</a></span></i></li>
            
            <li class="list-item"><i class="fa fa-envelope fa-2x"><span class="contact-text gmail"><a href="mailto:#" title="Send me an email">hitmeup@gmail.com</a></span></i></li>
            
          </ul>
  
          <hr>
          <ul class="social-media-list">
            <li><a href="#" target="_blank" class="contact-icon">
              <i class="fab fa-facebook" aria-hidden="true"></i></a>
            </li>
            <li><a href="#" target="_blank" class="contact-icon">
              <i class="fab fa-youtube" aria-hidden="true"></i></a>
            </li>
            <li><a href="#" target="_blank" class="contact-icon">
              <i class="fab fa-vimeo" aria-hidden="true"></i></a>
            </li>
            <li><a href="#" target="_blank" class="contact-icon">
              <i class="fab fa-instagram" aria-hidden="true"></i></a>
            </li>       
          </ul>
          <hr>
  
          <div class="copyright">&copy; ALL OF THE RIGHTS RESERVED</div>
  
        </div>
      
    </div>
    
  </section>  
    

{% endblock content %}

templates/base/insta.html
{% extends 'base.html' %}
{% load instagram_client %}
{% load static instagram_client %}
{% load static %}

{% block content %}

<section id="contact mt-4" >

{% if recent_media %}
    <div class="django_instagram">
        <ul class="slider">
            {% for media in recent_media %}
            <li class="entry">
                <a href="{{ media.display_src }}" title="{{ media.caption }}" target="_blank">
                    <img src="{{ media.thumbnail_src }}"/>
                </a>
            </li>
            {% endfor %}
        </ul>
    </div>
{% endif %}

<link href="{% static 'django_instagram/css/slider.css' %}" rel="stylesheet" type="text/css"/>
<script src="{% static 'django_instagram/js/slider.js' %}"></script>
    <div id="django_recent_media_wall" class="container ">
        <div class="row" style="margin:70px auto">
        <h3> @{{instagram_profile_name}} Instagram Feed</h3>
        {% instagram_user_recent_media instagram_profile_name %}
        {% for media in recent_media %}
            <div class="django_instagram_media_wall_item col-lg-3 col-md-4 col-sm-6 col-xs-12">
                <a href="//instagram.com/p/{{ media.shortcode }}" target="_blank">
                    {{ media.display_src }}
                    <img src="{{ media.thumbnail_src }}" width="100%" height="100%"  style="object-fit:contain">
                    <figcaption>{{ media.edge_media_to_caption.edges.0.node.text }}</figcaption>
                </a>
            </div>
        {% endfor %}
    </div>
</div>
</section>
<p>Got from instagram</p>

{% endblock %}

templates/base/partials/carousel.html
<header id="home" class="header">
  <!-- =============== container =============== -->
      <div class="container">
      <div class="header-content row">   

      <div id="owl-demo" class="owl-carousel header1">
        <div>
        <div class="col-xs-12 col-sm-6 col-md-6 header-text">
          <h2 class="wow bounceIn animated" data-wow-delay=".20s">PHOTOGRAPHY <br> <span>TO THE</span> NEXT LEVEL</h2>
          <h3 class="wow bounceIn animated" data-wow-delay=".30s">FOR YOU CREATION </h3>
          <p class="wow bounceIn animated" data-wow-delay=".40s">Lorem ipsum dolor sit amet, consectetur adipiscing elit.We ensure sit amet, consectetur adipiscing elit</p>
          <p>
              <a href='{% url "base:works" %}' class="btn btn-primary btn-lg btn-ornge wow bounceIn animated" data-wow-delay="1s"><i class="hbtn"></i> <span>Click Here</span></i>
              </a>
          </p>
        </div>               
      </div>
       <div>
        <div class="col-xs-12 col-sm-6 col-md-6 header-text">
          <h2 class="wow bounceIn animated" data-wow-delay=".40s">VIDEO  <br> <span>TO THE</span> NEXT LEVEL</h2>
          <h3 class="wow bounceIn animated" data-wow-delay=".50s">FOR YOU CREATION </h3>
          <p class="wow bounceIn animated" data-wow-delay=".60s">Lorem ipsum dolor sit amet, consectetur adipiscing elit.We ensure sit amet, consectetur adipiscing elit</p>
          <p>
              <a href='{% url "base:videos" %}' class="btn btn-primary btn-lg btn-ornge wow bounceIn animated" data-wow-delay="1s"><i class="hbtn"></i> <span>Click Here</span></i>
              </a>
          </p>
        </div>               
      </div>
      </div>				 
      </div>


              
      </div>
  <!-- =============== container end =============== -->
  </header>

templates/base/video.html
{% extends 'base.html' %}
{% load static %}
{% load embed_video_tags %}

{% load cache %}

{% cache 500 content %}

{% block content %}
<link rel="stylesheet" href="{% static 'css/work.css' %}">

<style>
    .cardy {
        --card-gradient: rgba(0, 0, 0, 0.8);
        --card-gradient: #5e9ad9, #e271ad;
        --card-blend-mode: overlay;
        background-color: #fff;
        border-radius: 0.5rem;
        box-shadow: 0.05rem 0.1rem 0.3rem -0.03rem rgba(0, 0, 0, 0.45);
        padding-bottom: 1rem;
        background-image: linear-gradient(var(--card-gradient), white max(9.5rem, 27vh));
        overflow: hidden;
        margin-top: 70px;
      }
      .cardy img {
        border-radius: 0.5rem 0.5rem 0 0;
        width: 100%;
        -o-object-fit: cover;
           object-fit: cover;
        max-height: max(10rem, 30vh);
        aspect-ratio: 4/3;
        mix-blend-mode: var(--card-blend-mode);
      }
      .cardy img ~ * {
        margin-left: 1rem;
        margin-right: 1rem;
      }
      .cardy > :last-child {
        margin-bottom: 0;
      }
      .cardy:hover, .cardy:focus-within {
        --card-gradient: #24a9d5 max(8.5rem, 20vh);
      }
      
      /* Additional demo display styles */
      * {
        box-sizing: border-box;
      }
    
      
      .cardy h3 {
        margin-top: 1rem;
        font-size: 1.25rem;
      }
      
      .cardy a {
        color: inherit;
      }
      
      .cardy-wrapper {
        list-style: none;
        padding: 0;
        margin: 0;
        display: grid;
        grid-template-columns: repeat(auto-fit, minmax(30ch, 1fr));
        grid-gap: 1.5rem;
        max-width: 100vw;
        width: 90ch;
        padding-left: 1rem;
        padding-right: 1rem;
      }
</style>



<div class="container mt-4" style='margin: 70px auto'>
    <div class="row" style='width:100%'>
        <ul class="cardy-wrapper">
        {% if v|length > 0 %}
            {% for item in v %}
                {% video item.video_url as my_video %}
                <a href="{% url 'base:video-details' item.uuid %}">
                    <li class="cardy">
                        <img src='{{ my_video.thumbnail }}' alt=''>
                        <h3>{{ item.title }}</h3>
                    </li>
                </a>
                {% endvideo %}   
            {% endfor %}   
        {% endif %}
        </ul>
    </div>
</div>



{% endblock %}
{% endcache %}

templates/base/video_details.html
{% extends 'base.html' %}
{% load static %}
{% load embed_video_tags %}

{% block content %}

<style>
    @import url("https://fonts.googleapis.com/css2?family=Montserrat:wght@100;400;800&display=swap");

body,
html {
	background: #fff;
	padding: 0;
	margin: 0;
	padding-bottom: 6rem;
	font-family: "Montserrat", sans-serif;
	width: 100%;
	color: #000;
}
.container_ {
	padding-bottom: 3rem;
}
img {
	-webkit-box-reflect: below 5px
		linear-gradient(transparent, transparent, rgba(0, 0, 0, 0.4));
	-webkit-transition: all 0.5s ease;
	-o-transition: all 0.5s ease;
	transition: all 0.5s ease;
}
.container_ img:hover {
	-webkit-transform: scale(1.1);
	-ms-transform: scale(1.1);
	transform: scale(1.1);
}
.last {
	margin-top: 6.5rem;
}
.featured_wrapper {
	position: relative;
}
.featured_wrapper img {
	width: 100%;
	width: 100%;
	height: 350px;
	-o-object-fit: cover;
	object-fit: cover;
	-o-object-position: top;
	object-position: top;
}
.title_wrapper {
	position: absolute;
	width: 100%;
	left: 2rem;
	bottom: 2rem;
	padding: 20px 40px;
	-webkit-box-sizing: border-box;
	box-sizing: border-box;
}
.title_wrapper h1 {
	width: 70%;
}
button {
	background: #f40612 !important;
	color: #fff !important;
	font-size: 18px;
	padding: 0.5rem 3rem;
	outline: none;
	border: 0 !important;
}
@media (max-width: 768px) {
	.title_wrapper {
		text-align: center;
		left: 0;
	}
	.title_wrapper h1 {
		font-size: 32px !important;
		width: 100%;
	}
	.container_ {
		padding: 20px;
	}
}
@media (max-width: 480px) {
	.column.is-one-quarter img {
		width: 100%;
		margin-bottom: 7rem;
	}
}

</style>


<div class="row w-100 m-auto" style='margin: 80px auto'>
    <div class="col-lg-12 col-md-6 col-sm-12 d-flex justify-content-between">

        <!-- #CodePenChallenge: Reflections -->
<div class="top">
	<div class="columns">
		<div class="column is-full featured_wrapper p-0">
			{% comment %} <img src="https://raw.githubusercontent.com/brixiobodino/coffeholic/main/banner.jpg" class="featured"> {% endcomment %}
			{% video v.video_url '1500x550' %}
			<div class="title_wrapper">
				{% comment %} <span class="has-text-white">Trending Today</span>
				<h1 class="title is-2 has-text-white">{{v.title}}</h1>
				<button class="button is-medium">Watch It Now</button> {% endcomment %}
			</div>
		</div>
	</div>
</div>


<div class="container_ " style="border-bottom: 2px solid black">
	<div class="container pb-4">
	<div class="row">
		<div class="card text-center">
		  <div class="card-header">
			<ul class="nav nav-tabs card-header-tabs">
			  <li class="nav-item">
				<a class="nav-link active" href="">Description</a>
			  </li>
			</ul>
		  </div>
		  <div class="card-body text-left">
			<h4 class="card-title">{{v.title}}</h4>
			<p class="card-text">{{v.details|safe}}</p>
		  </div>
		</div>
	</div>
	</div>
	<hr style="border-bottom: 2px solid black">
	<div class="columns is-multiline p-0 last row ">
		<div class="column is-full col-sm-12 border-top">
			<h2 class="has-text-white">Related Videos</h2>
		</div>
		{% if related_videos|length > 0 %}
			{% for item in related_videos %}
				{% video item.video_url as my_video %}
					{% if item.video_url != v.video_url %}
						<div class="column col-md-3 col-sm-12">
							<a href="{% url 'base:video-details' item.uuid %}">
								<li class="cardy">
									<img src='{{ my_video.thumbnail }}' alt='' width="100%">
								</li>
							</a>
						</div>
					{% endif %}
				{% endvideo %}   
			{% endfor %}   
		{% endif %}
		</div>
	</div>
</div>

        <!-- <div class="container" >     -->
            <!-- <div class="card">
                <div class="card-body">
                    <h2>{{v.title}}</h2>
                </div>
            </div>
            <div class="card" >
                <div class="card-body">
                    <h1>{% video v.video_url '1500x800' %}</h1>
                </div>
            </div> -->
        <!-- </div> -->
        <!-- <div class="card bg-primary text-white">
            <div class="card-header" style="padding:20px">
                <h2 class=''>Video details</h2>
            </div>
            <div class="card-body">
                <h5>{{v.details}}</h5>
            </div>
        </div> -->

    <!-- </div> -->
    <!-- <div class="col-lg-3 col-md-6 col-sm-12 ">
        <
    </div> -->
</div>

{% endblock content %}

templates/includes/top-nav.html
<nav id="mainNav" class="navbar navbar navbar-dark navbar-fixed-top" style='z-index:20; background: black !important'>
        <div class="container">
            <div class="container-fluid">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#"><img src="../../static/images/cp-logo.jpeg " alt="Logo" width='70' height='70' style='object-fit:contain; border:2px solid #0482d9; border-radius:50%'>
                    </a>
                </div>

                <!-- Collect the nav links, forms, and other content for toggling -->

                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav navbar-right">
						<li >
                            <a class="page-scroll" style='color:white !important; ' href="{% url 'base:index' %}">Home</a>
                        </li>
                        <li>
                            <a class="page-scroll" href="{% url 'base:about' %}">About</a>
                        </li>
                        <li>
                            <a class="page-scroll" href="#Services">Services</a>
                        </li>
                        <li>
                            <a class="page-scroll" href="{% url 'base:works' %}">Collage</a>
                        </li>
                        <li>
                            <a class="page-scroll" href="{% url 'base:videos' %}">Videos</a>
                        </li>
                        <li>
                            <a class="page-scroll" href="{% url 'base:contact' %}">Contact</a>
                        </li>
                    </ul>
                </div>
                <!-- =============== navbar-collapse =============== -->

            </div>
        </div>
        <!-- =============== container-fluid =============== -->
    </nav>